[workspace]
authors = ["johnsoez4 <johnsoez4@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo_test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tests = "sh test.sh"
update = "sh update.sh"

[dependencies]
mojo = "<1.0.0"
